{% set name = "SQLAlchemy" %}
{% set version = "1.2.2" %}
{% set sha256 = "64b4720f0a8e033db0154d3824f5bf677cf2797e11d44743cf0aebd2a0499d9d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - mock  # [py27]
  imports:
    - sqlalchemy
    - sqlalchemy.connectors
    - sqlalchemy.databases
    - sqlalchemy.dialects
    - sqlalchemy.dialects.firebird
    - sqlalchemy.dialects.mssql
    - sqlalchemy.dialects.mysql
    - sqlalchemy.dialects.oracle
    - sqlalchemy.dialects.postgresql
    - sqlalchemy.dialects.sqlite
    - sqlalchemy.dialects.sybase
    - sqlalchemy.engine
    - sqlalchemy.event
    - sqlalchemy.ext
    - sqlalchemy.ext.declarative
    - sqlalchemy.orm
    - sqlalchemy.sql
    - sqlalchemy.testing
    - sqlalchemy.testing.plugin
    - sqlalchemy.util

about:
  home: http://www.sqlalchemy.org/
  license: MIT
  license_file: LICENSE
  summary: 'Database Abstraction Library.'
  description: |
    SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that
    gives application developers the full power and flexibility of SQL.
  doc_url: http://docs.sqlalchemy.org/en/rel_1_0/
  dev_url: https://bitbucket.org/zzzeek/sqlalchemy/
  doc_source_url: https://github.com/zzzeek/sqlalchemy/blob/master/doc/build/index.rst

extra:
  recipe-maintainers:
    - ocefpaf
    - mcs07
    - nehaljwani
    - igortg
