travis:
  secure:
    BINSTAR_TOKEN: XAtm7xmAKa4F0tWz2TlVIFNB436oQaG157uzRDALHYk8AOYrySYQUZw9/BMbZuXEhwvPM3+FWA38Kk9jdjqF8oQAgdEcbxt9qsQU/mpHF7N5TgvD9dgakxdIawVzVePlavJdP4jh9JiGnyqhIc47aRq8rcDo1/u37GYoAAUXI7/JloDvg51K+a1ngZ6F8RDAwsXKRh14KNUFXmLxHNt8aj/EXwO47rqUwbXEJ30GppN9ezcgxL92qTTIiUGExFjBsUnzXmkEHKhyX2z+jvpNk0hRwpBEUF8YlNs2K/28rY6vCNYd5l/BLvVPAeCmTbkQrRxHWrShi71WJfUctnBGfM6DPyO/Zbr8x9Efpg1H9vHpT10c6JBKq5gpeVV1p1Iug3fixr/FTIjmHPcFtcOnf/FUYgXUfTyS3bfRKnQsny42tfmVNSMr4FVyRCfjQx2qI9zJXbcgNF/inXXkQzYLQI6gKhyT9pILSR5gn6pcvMRCoPGDm2UjWtI+WZ81KSyEWAGU4WOCYBtFGOIuy83+fqF3/wnDoarzSPW2u7WXf2HD2zDIhiw6RhCDTfLKTqi65100+Ql3mApmuG6FZT+EgnQiOWKfF3Sx/4zqBLhR+pD9L7OLpT4PGrF967JqV6PilbuS07ZIMU3DZ+Q1B1sttMRY4U55fYQLM05W0wGbdH8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: false
